# Generated by Django 4.1 on 2025-04-13 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("octofit_tracker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="activity",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="leaderboard",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="difficulty",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="duration",
        ),
    ]
